const $ = (s) => document.querySelector(s);
const inventoryForm = $("#inventory-form"), employeeForm = $("#employee-form"), appStatus = $("#app-status");
let inventory = [], employees = [], currentUser, users = [];
const say = (m) => { appStatus.textContent = ""; requestAnimationFrame(() => appStatus.textContent = m); };
const text = (tag, value) => { const el = document.createElement(tag); el.textContent = value; return el; };
async function api(path, options = {}) { const r = await fetch(path, { ...options, headers: { "content-type": "application/json", ...(options.headers || {}) } }); if (r.status === 401) return location.assign("/login"); if (!r.ok) throw new Error((await r.json().catch(() => ({}))).error || "Request failed."); return r.status === 204 ? null : r.json(); }
function resetInventory() { inventoryForm.reset(); $("#record-id").value = ""; $("#inventory-form-heading").textContent = "Add an inventory item"; $("#submit-button").textContent = "Add item"; $("#cancel-button").hidden = true; }
function resetEmployee() { employeeForm.reset(); $("#employee-id").value = ""; $("#employee-form-heading").textContent = "Add an employee"; $("#employee-submit-button").textContent = "Add employee"; $("#employee-cancel-button").hidden = true; }
function button(label, callback) { const el = text("button", label); el.type = "button"; el.addEventListener("click", callback); return el; }
function renderInventory() { const list = $("#inventory-list"); list.replaceChildren(); $("#empty-message").hidden = inventory.length > 0; inventory.forEach((item) => { const person = employees.find((e) => e.id === item.employeeId); const row = document.createElement("li"); row.className = "inventory-item"; row.append(text("h3", item.name), text("p", item.description), text("p", `Status: ${item.status}`), text("p", `Assigned to: ${person ? person.name : "Unassigned"}`)); const control = document.createElement("div"); control.className = "assignment-control"; const label = text("label", `Assign ${item.name}`), select = document.createElement("select"); label.htmlFor = select.id = `assignment-${item.id}`; select.append(new Option("Unassigned", "")); employees.forEach((e) => select.append(new Option(`${e.name} (${e.email})`, e.id))); select.value = item.employeeId || ""; select.addEventListener("change", () => request(`/api/inventory/${item.id}/assignment`, "PUT", { employeeId: select.value ? Number(select.value) : null }, "Assignment updated.")); control.append(label, select); const actions = document.createElement("div"); actions.className = "item-actions"; actions.append(button("Edit", () => { $("#record-id").value = item.id; $("#name").value = item.name; $("#description").value = item.description; $("#status").value = item.status; $("#inventory-form-heading").textContent = "Edit inventory item"; $("#submit-button").textContent = "Save changes"; $("#cancel-button").hidden = false; }), button("Delete", () => confirm(`Delete ${item.name}? This cannot be undone.`) && request(`/api/inventory/${item.id}`, "DELETE", null, `${item.name} deleted.`))); row.append(control, actions); list.append(row); }); }
function renderEmployees() { const body = $("#employees-table-body"); body.replaceChildren(); $("#employees-empty-message").hidden = employees.length > 0; $("#employees-table-wrapper").hidden = !employees.length; employees.forEach((employee) => { const row = document.createElement("tr"), actions = document.createElement("td"); row.append(text("td", employee.name), text("td", employee.email)); actions.append(button("Edit", () => { $("#employee-id").value = employee.id; $("#employee-name").value = employee.name; $("#employee-email").value = employee.email; $("#employee-form-heading").textContent = "Edit employee"; $("#employee-submit-button").textContent = "Save changes"; $("#employee-cancel-button").hidden = false; }), button("Delete", () => confirm(`Delete ${employee.name}? Assigned items will be returned to unassigned.`) && request(`/api/employees/${employee.id}`, "DELETE", null, `${employee.name} deleted.`))); row.append(actions); body.append(row); }); }
function renderUsers() { const body = $("#users-table-body"); body.replaceChildren(); $("#users-empty-message").hidden = users.length > 0; $("#users-table-wrapper").hidden = !users.length; users.forEach((user) => { const row = document.createElement("tr"), actions = document.createElement("td"); row.append(text("td", user.email), text("td", user.isAdmin ? "Administrator" : "User")); const role = button(user.isAdmin ? "Revoke admin" : "Grant admin", () => manage(user, "PATCH", { isAdmin: !user.isAdmin }, `${user.isAdmin ? "Revoke" : "Grant"} administrator access for ${user.email}?`)), remove = button("Delete", () => manage(user, "DELETE", null, `Delete ${user.email}? This cannot be undone.`)); role.disabled = remove.disabled = user.id === currentUser.id; actions.append(role, remove); row.append(actions); body.append(row); }); }
async function refresh() { [inventory, employees] = await Promise.all([api("/api/inventory").then((v) => v.inventory), api("/api/employees").then((v) => v.employees)]); renderInventory(); renderEmployees(); }
async function refreshUsers() { users = (await api("/api/admin/users")).users; renderUsers(); }
async function request(path, method, body, message) { try { await api(path, { method, body: body && JSON.stringify(body) }); await refresh(); if (currentUser.isAdmin) await refreshUsers(); say(message); return true; } catch (e) { say(e.message); return false; } }
async function manage(user, method, body, prompt) { if (!confirm(prompt)) return; try { await api(`/api/admin/users/${user.id}`, { method, body: body && JSON.stringify(body) }); await refreshUsers(); say("User administration updated."); } catch (e) { $("#admin-status").textContent = e.message; $("#admin-status").hidden = false; } }
inventoryForm.addEventListener("submit", (e) => { e.preventDefault(); const id = $("#record-id").value, name = $("#name").value.trim(), description = $("#description").value.trim(); if (!name || !description) return inventoryForm.reportValidity(); request(id ? `/api/inventory/${id}` : "/api/inventory", id ? "PUT" : "POST", { name, description, status: $("#status").value }, `${name} ${id ? "updated" : "added"}.`).then((saved) => { if (saved) resetInventory(); }); });
employeeForm.addEventListener("submit", (e) => { e.preventDefault(); const id = $("#employee-id").value, name = $("#employee-name").value.trim(), email = $("#employee-email").value.trim(); if (!name || !email) return employeeForm.reportValidity(); request(id ? `/api/employees/${id}` : "/api/employees", id ? "PUT" : "POST", { name, email }, `${name} ${id ? "updated" : "added"}.`).then((saved) => { if (saved) resetEmployee(); }); });
$("#cancel-button").addEventListener("click", resetInventory); $("#employee-cancel-button").addEventListener("click", resetEmployee);
$("#sign-out-button").addEventListener("click", async () => { await api("/api/session", { method: "DELETE" }); location.assign("/login"); });
$("#user-form").addEventListener("submit", async (e) => { e.preventDefault(); $("#admin-status").hidden = true; try { await api("/api/admin/users", { method: "POST", body: JSON.stringify({ email: $("#user-email").value, password: $("#user-password").value, isAdmin: $("#user-admin").checked }) }); e.target.reset(); await refreshUsers(); say("User created."); } catch (err) { $("#admin-status").textContent = err.message; $("#admin-status").hidden = false; } });
(async () => { currentUser = (await api("/api/me")).user; if (currentUser.isAdmin) { $("#admin-panel").hidden = false; await refreshUsers(); } await refresh(); })().catch((e) => say(e.message));
